console.log("Wlecome to ZeroOne");
let a = "ZeroOne";
a = 10;
console.log(a);
const name = "Nirbhay";
let id = 2300090360;
let branch = "CSIT";
console.log("name");
console.log(id);
console.log(brach);